---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data(instacart)

set.seed(1)

sample_instacart = instacart[sample(nrow(instacart), 1000), ]
```

Column {data-width = 650}
-----------------------------------------------------------------------

### Chart A

```{r}
order_aisles = sample_instacart %>%
  select(., aisle, product_id) %>%
  arrange(., aisle, product_id) %>%
  group_by(aisle) %>%
  summarise(item_num = n()) %>%
  arrange(., desc(item_num))

plot_ly(order_aisles, x = ~reorder(aisle, -item_num), y = ~item_num, type = "scatter", mode = "markers", alpha = 0.5) %>%
  layout(xaxis = list(title = 'aisle'), yaxis = list(title = 'number of item'))
```

Column {data-width = 350}
-----------------------------------------------------------------------

### Chart B

```{r}
order_day = sample_instacart %>%
  select(order_dow) %>%
  group_by(order_dow) %>%
  summarise(day_num = n()) %>%
  ungroup() %>%
  mutate(day = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")) %>%
  mutate(day = factor(day, levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")))

plot_ly(order_day, x = ~day, y = ~day_num, color = ~day, type = "bar") %>%
  layout(xaxis = list(title = 'day'), yaxis = list(title = 'total day number'))
```

### Chart C

```{r}
hour_day = sample_instacart %>%
  select(order_hour_of_day) %>%
  group_by(order_hour_of_day) %>%
  summarise(hour_num = n())

plot_ly(hour_day, x = ~order_hour_of_day, y = ~hour_num, type = 'scatter', mode = 'lines') %>%
  layout(xaxis = list(title = 'day'), yaxis = list(title = 'total day number'))
```
